# Generated by Django 4.2.16 on 2024-12-09 00:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.TextField(blank=True)),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=200)),
                ('button_url', models.URLField()),
                ('button_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.TextField()),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=200)),
                ('button_url', models.URLField()),
                ('button_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.TextField()),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=200)),
                ('button_url', models.URLField()),
                ('button_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.TextField(blank=True)),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=200)),
                ('button_url', models.URLField()),
                ('button_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
