# Generated by Django 4.2.16 on 2024-12-06 14:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('cta_image_alt', models.TextField(blank=True)),
                ('cta_heading', models.CharField(max_length=200)),
                ('cta_text', models.TextField()),
                ('cta_button_text', models.CharField(max_length=200)),
                ('cta_button_url', models.URLField()),
                ('cta_button_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('hero_image_alt', models.TextField()),
                ('hero_heading', models.CharField(max_length=200)),
                ('hero_text', models.TextField()),
                ('hero_button_text', models.CharField(max_length=200)),
                ('hero_button_url', models.URLField()),
                ('hero_button_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
